### PR TITLE
add patch to remove region restriction on xCloud

### PR DESCRIPTION
**Pull request by pccr10001**

### CODE REVIEW

**Comment by MeGaPk** [comment]
tested on Chrome with ModHeader, this hack works great!

**Comment by FatCache** [comment]
I think there is an issue with your PR. The electron store does not quiet work. I get this 

```
Import trace for requested module:
../node_modules/atomically/dist/index.js
../node_modules/conf/dist/source/index.js
../node_modules/electron-store/index.js
./context/userContext.tsx
./pages/_app.tsx
```

Any idea?

**Comment by Originalimoc** [comment]
@FatCache I guess no "store" defined in main/helpers/authentication.ts(now main/authentication.ts)? Or this https://github.com/sindresorhus/electron-store/issues/213

**Comment by unknownskl** [comment]
Already merged in #1053. Thanks for the contribution!

**Pull request closed without merging**
