### PR TITLE
Flatpak manual build script and AMD VAAPI fix

### PR DESCRIPTION
**Pull request by Originalimoc**
replace #993, include #1052 from @FatCache

### CODE REVIEW

**Comment by FatCache** [comment]
Woah, nice. New to git way of working, any specific details why you opt to pull changing from my branch into you're?

Looks good! There is another change by another contributor that removes "region lock" it would be nice to merge it.

Although I couldn't quite make it work since it complains about "electron storage".

**Comment by FatCache** [comment]
@Originalimoc  check this out

https://github.com/unknownskl/greenlight/pull/850

**Comment by Originalimoc** [comment]
You could try
````
headers = {
                    "X-Forwarded-For": store.get("force_region"),
                };
            }

            this.request(options, data, headers).then((response:any)
````
This part first, see if MS still allow this header. Choose a IP from 850 below to replace "store.get("force_region")"

**Comment by Originalimoc** [comment]
@FatCache Here, but with a bug not solved, you need restart twice every time you changes region. 1st for write to config store, 2nd for loading that store.

**Comment by unknownskl** [comment]
Thanks for the PR! Will get this merged and sort out the bug :)

**Comment by unknownskl** [comment]
I've added a patch to reload the tokens once switching the region. Does that fix the restart bug?

**Comment by Originalimoc** [comment]
Good as I didn't really know the whole project code structure and exactly how Electron works. I tested and region/IP is now loaded as choice made. Now xCloud page need a refresh if it's already loaded. I've updated the driver submodule and later edit Readme for instruction and add a flatpak launch script with correct arguments because still need test if scaling filter is corrected but I don't have access to my Deck right now.

**Pull request merged**
