### PR TITLE
Update bitrate selector/editor

### PR DESCRIPTION
**Pull request by kohanyirobert**
I've reworked the stream quality/bitrate settings, turned them from text boxes to sliders with discrete values. For me it helped when playing with quality settings.

image

### CODE REVIEW

**Comment by unknownskl** [comment]
Thanks! This is much better UX wise

**Comment by ThumbUPed** [comment]
Hello thx for good work, Pls tell me how i can change quality to low and change frame rate? Pls help me change to low frame rate and low resolution. I play from notebook with my son and i need low frame rate and resolution that i can play games.

**Comment by kohanyirobert** [comment]
@ThumbUPed Sorry but this PR only changed the way one would set the _bitrate_ (not the framerate or resolution) for xCloud and xHome sessions. I'm not sure what/why you ask it. Please open a different issue for your exact question (what is that you try to achieve, why, how? what have you tried? etc.).

**Comment by ThumbUPed** [comment]
> @ThumbUPed Sorry but this PR only changed the way one would set the _bitrate_ (not the framerate or resolution) for xCloud and xHome sessions. I'm not sure what/why you ask it. Please open a different issue for your exact question (what is that you try to achieve, why, how? what have you tried? etc.).

Hello! Thx for your answer my friend! 
Before the February console update, I used the xbox companion app for streaming. In the xbox companion app, after the February update, the stream function was disabled. Since I have a weak laptop, the xbox companion app had a low-normal-good-very good stream function. I used the low function to stream on the laptop without lags. Now when i using the usual xbox stream app there are no such functions as in your app unfortunately. Is it possible to configure the resolution and frame rate in some file? I would not like to change the laptop, I am ready to pay you money better if you can help.

**Comment by kohanyirobert** [comment]
Well, if you install this app and then set the bitrate to something like 5 to 10 mbps it would have a similar effect. Other than this I can't help even if money is involved.

**Comment by ThumbUPed** [comment]
> Well, if you install this app and then set the bitrate to something like 5 to 10 mbps it would have a similar effect. Other than this I can't help even if money is involved.

"set the bitrate to something like 5 to 10 mbps it would have a similar effect" - sorry but 5-10 or 100 work the same i think that it's bitrate not work

**Comment by unknownskl** [comment]
> > Well, if you install this app and then set the bitrate to something like 5 to 10 mbps it would have a similar effect. Other than this I can't help even if money is involved.
> 
> "set the bitrate to something like 5 to 10 mbps it would have a similar effect" - sorry but 5-10 or 100 work the same i think that it's bitrate not work

There is no way to set the resolution with this protocol. Please keep your problem in your issue and don't pollute closed pr's please.

**Pull request merged**
